### ISSUE TITLE
coloring

### ISSUE THREAD

**Issue by DPijnenburg** [tercen/mean_and_cv_shiny_operator#4]
Multiple factors for coloring does not work . 

For example is sample is annotated with cell line (A, B) and treatment (C, T) we should get 4 CV plots when coloring by both factors. It picks up only the top annotation.

https://tercen.com/PamgeneEvaluators/w/ebd643c3119c715cacdef627bb1bfa55/ds/5219426d-680c-4467-88a9-1db09826384b/crosstab

**Comment by ginberg** [comment]
@DPijnenburg this should be fixed in latest version
